name: Github actions 202
run-name: ${{ github.actor }} apply 🚀
on: 
  push:
    branches:
      - main
      - dev
    paths:
      - 'infrastructure/**'
env:
  CONFIG_DIRECTORY: "infrastructure"
  TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
  TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  Terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ env.CONFIG_DIRECTORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
      - name: Terraform Init
        id: init
        run: terraform init
  
      - name: Terraform Apply
        run: terraform plan -no-color