name: PR
run-name: ${{ github.actor }} created pull request from ${{ github.head_ref }} to ${{ github.base_ref }} 🚩

on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, reopened]
   
env:
  TF_CLOUD_ORGANIZATION: DACN
  TF_CLOUD_PROJECT: UIT
  branch: ${{ github.base_ref }}
  environment: ${{ github.base_ref == 'main' && 'prod' || 'dev' }} 

jobs:
  Plan-infrastructure:
    name: "Planning for infrastructure implement"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
      - name: Terraform Plan
        id: plan
        working-directory: "./test_infra/"
        env:
          TF_WORKSPACE: ${{ format('infra-{0}', env.environment) }}
          TF_CLI_ARGS: ${{ format('-no-color -var-file=./environments/{0}/terraform.tfvars', env.environment) }}
        run: |
          terraform init > .nothing
          terraform plan > output
          url=$(grep '^To view this run in a browser, visit:' -A1 output | grep -v '^To view this run in a browser, visit:' | tr -d '\012\015')
          sm=$(grep -E '^(Plan:|No changes.)' output | tr -d '\012\015')
          echo "run_link=$url" >> $GITHUB_OUTPUT
          echo "summary=$sm" >> $GITHUB_OUTPUT
          echo "Run link: $url"
          echo "Summary: $sm"
          
      - name: Write pull request comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Run-link: ${{ steps.plan.outputs.run_link }}
            #### Summary: \`${{ steps.plan.outputs.summary }}\``;
            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
            })

  Plan-application:
    name: Planing for application deployment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      TF_CLI_ARGS: -no-color
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform get infrastructure outputs
        id: get-output
        working-directory: ./test_infra/
        env:
          TF_WORKSPACE: ${{ format('infra-{0}', env.environment) }}
        run: |
          terraform init > .nothing
          if terraform output > infra_outputs_file 2>&1;then
          echo "output error."
          else
          echo "output success."
          fi
          if [ grep -q "could not read state version outputs: resource not found" infra_outputs_file;then
          cluster_built=false
          echo "infra not built"
          else
          cluster_built=true
          echo "infra built"
          echo 'infra_outputs<<EOF' >> $GITHUB_ENV
          cat infra_outputs_file >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          fi
          echo "cluster_built=$cluster_built" >> $GITHUB_ENV

      - name: Terraform plan for application deployment
        id: plan
        if: ${{ env.cluster_built }}
        working-directory: ./test_app/
        env:
          TF_WORKSPACE: ${{ format('app-{0}', env.environment) }}
        run: |
          echo $infra_outputs > terraform.tfvars
          terraform init > .nothing
          terraform plan > plan_output
          url=$(grep '^To view this run in a browser, visit:' -A1 plan_output | grep -v '^To view this run in a browser, visit:' | tr -d '\012\015')
          sm=$(grep -E '^(Plan:|No changes.)' plan_output | tr -d '\012\015')
          echo "run_link=$url" >> $GITHUB_OUTPUT
          echo "summary=$sm" >> $GITHUB_OUTPUT
          echo "Run link: $url"
          echo "Summary: $sm"

      - name: Write pull request comment
        if: ${{ env.cluster_built }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Run-link: ${{ steps.plan.outputs.run_link }}
            #### Summary: \`${{ steps.plan.outputs.summary }}\``;
            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
            })
  
  # Test-chart:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: Set up Helm
  #       uses: azure/setup-helm@v4.2.0
  #       with:
  #         version: v3.14.4

  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.x'
  #         check-latest: true

  #     - name: Set up chart-testing
  #       uses: helm/chart-testing-action@v2.7.0

  #     - name: Run chart-testing (list-changed)
  #       id: list-changed
  #       run: |
  #         changed=$(ct list-changed --config ct.yaml --target-branch $branch)
  #         if [[ -n "$changed" ]]; then
  #           echo "changed=true" >> "$GITHUB_OUTPUT"
  #         fi

  #     - name: Run chart-testing (lint)
  #       if: steps.list-changed.outputs.changed == 'true'
  #       run: ct lint --config ct.yaml --target-branch $branch

  #     - name: Create kind cluster
  #       if: steps.list-changed.outputs.changed == 'true'
  #       uses: helm/kind-action@v1.10.0

  #     - name: Run chart-testing (install)
  #       if: steps.list-changed.outputs.changed == 'true'
  #       run: ct install --config ct.yaml --target-branch $branch
    
  # Test-image:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #   defaults:
  #     run:
  #       working-directory: "./application/"

  #   strategy:
  #     matrix:
  #       node: [ 16, 18, 20 ]
  #   name: Node ${{ matrix.node }} sample

  #   steps:
  #     - uses: actions/checkout@v4.1.1

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node }} 

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Unit test
  #       run: npm run test