name: destroy workflow
run-name: ${{ github.actor }} destroy branch ${{ github.ref_name }}💥

on:
  workflow_dispatch:
      
env:
  TF_CLOUD_ORGANIZATION: DACN
  TF_CLOUD_PROJECT: UIT
  environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

jobs:
  app_destroy:
    name: Destroy application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test_app
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -destroy -out plan.json > .output
          url=$(grep '^To view this run' -A1 .output | grep -v '^To view this run' | tr -d '\012\015')
          sm=$(grep -E '^(Plan:|No changes.)' .output | tr -d '\012\015')
          echo "Run link: $url"
          echo "Summary: $sm"
          
          echo "summary=$sm" >> $GITHUB_OUTPUT
          
      - name: Terraform Apply
        if: ${{ !startsWith(steps.plan.outputs.summary, 'No changes.') }}
        run: |
          terraform apply plan.json -no-color > output
          echo "Run link: $(grep '^To view this run' -A1 output | grep -v '^To view this run' | tr -d '\012\015')"
          echo "Summary: $(grep -E '^(Apply complete!|No changes.)' output | tr -d '\012\015')"

  infra_destroy:
    name: Destroy infrastructure
    needs: app_destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test_infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -destroy -out plan.json -var-file=./environments/$environment/terraform.tfvars > .output
          url=$(grep '^To view this run' -A1 .output | grep -v '^To view this run' | tr -d '\012\015')
          sm=$(grep -E '^(Plan:|No changes.)' .output | tr -d '\012\015')
          echo "Run link: $url"
          echo "Summary: $sm"
          
          echo "summary=$sm" >> $GITHUB_OUTPUT
          
      - name: Terraform Apply
        if: ${{ !startsWith(steps.plan.outputs.summary, 'No changes.') }}
        run: |
          terraform apply plan.json -no-color > output
          echo "Run link: $(grep '^To view this run' -A1 output | grep -v '^To view this run' | tr -d '\012\015')"
          echo "Summary: $(grep -E '^(Apply complete!|No changes.)' output | tr -d '\012\015')"
